Params:
  title: "SimpleK8s"
  titleSeparator: "-"
  titleAddition: "Linux distribution for effortless Kubernetes clusters"
  description: "A lightweight Linux distribution for effortless Kubernetes clusters."
  options:
    bootStrapJs: true
