Menus:
  main:
    - Name: Home
      URL: /
      Weight: 100
    - Name: Download
      URL: /download/
      Weight: 90
    - Name: Documentation
      URL: /documentation/
      Weight: 80
    - Name: News
      URL: /news/
      Weight: 70
    - Name: Code
      URL: https://git.simplek8s.org
      Weight: 60

Params:
  title: "SimpleK8s"
  titleSeparator: "-"
  titleAddition: "Linux distribution for effortless Kubernetes"
  description: "A lightweight Linux distribution for effortless Kubernetes clusters."
  options:
    bootStrapJs: true
    breadCrumb: true
