baseURL = 'https://simplek8s.org'
locale = 'en-us'
title = 'SimpleK8s'
timeout = '120s'

[security.http]
mediaTypes = ['.*']

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'
